### ISSUE TITLE
摘要组件linux下错误

### ISSUE THREAD

**Issue by wubobuaa** [NLPIR-team/NLPIR#11]
windows下调用LJSummary.dll可以正常使用，linux 64位下使用libLJSummary.so报错，使用DS_Init初始化为false，DS_GetLastErrMsg打印结果为空
![image](https://cloud.githubusercontent.com/assets/2927031/14378089/ea516204-fda5-11e5-89cc-4a6fe1dce821.png)

**Comment by Dr-Kevin-Zhang** [comment]
麻烦查下 日志文件，应该在其中有缘由，可能是授权过期或者数据文件放置地方不对。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： Wu Bo
发送时间： 2016-04-08 16:22
收件人： NLPIR-team/NLPIR
主题： [NLPIR-team/NLPIR] 摘要组件linux下错误 (#11)
windows下调用LJSummary.dll可以正常使用，linux 64位下使用libLJSummary.so报错，使用DS_Init初始化为false，DS_GetLastErrMsg打印结果为空

**Comment by wubobuaa** [comment]
@Dr-Kevin-Zhang 报的错误是libLJSummary.so文件的错，可以正确loadLibrary，但是在init的时候出错，应该不是授权过期，因为在windows下可以正常使用，linux下只是用了相关的.so文件
![image](https://cloud.githubusercontent.com/assets/2927031/14382479/b2111220-fdc0-11e5-8bae-2db1d53689e5.png)

**Comment by anshe80** [comment]
本想偷懒用于多个句子的情感分析，但是突然多次调用情感分析的方法，会出现如下的错误，而单次调用则不会报错。
Exception in thread "main" java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:470)
	at com.sun.jna.Function.invokeString(Function.java:651)
	at com.sun.jna.Function.invoke(Function.java:395)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy1.NLPIR_ParagraphProcess(Unknown Source)
