### ISSUE TITLE
多次调用情感分析接口报错 Invalid memory access

### ISSUE THREAD

**Issue by anshe80** [NLPIR-team/NLPIR#12]
本想偷懒用于多个句子的情感分析，但是突然多次调用情感分析的方法，会出现如下的错误，而单次调用则不会报错。
Exception in thread "main" java.lang.Error: Invalid memory access
at com.sun.jna.Native.invokePointer(Native Method)
at com.sun.jna.Function.invokePointer(Function.java:470)
at com.sun.jna.Function.invokeString(Function.java:651)
at com.sun.jna.Function.invoke(Function.java:395)
at com.sun.jna.Function.invoke(Function.java:315)
at com.sun.jna.Library$Handler.invoke(Library.java:212)
at com.sun.proxy.$Proxy1.NLPIR_ParagraphProcess(Unknown Source)

**Comment by anshe80** [comment]
醉了！最后发现是同时使用了分词，这里的分词多次使用好像有问题。

**Comment by anshe80** [comment]
解决方式是：
初始化一次，添加判断是否所有的文档都已经分词完成，再关闭分词和情感分析。

**Comment by Dr-Kevin-Zhang** [comment]
只需要一份，如果需要多份，初始化只需要一次，可以采用多线程调用不同接口。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： anshe80
发送时间： 2016-04-12 19:55
收件人： NLPIR-team/NLPIR
主题： Re: [NLPIR-team/NLPIR] 多次调用情感分析接口报错 Invalid memory access (#12)
醉了！最后发现是同时使用了分词，这里的分词多次使用好像有问题。

**Comment by system63mush** [comment]
解决方式是：
初始化一次，添加判断是否所有的文档都已经分词完成，再关闭分词和情感分析。
这个具体是怎么解决的呢？求教

**Comment by anshe80** [comment]
我出现的问题是：先进行分词后，再进行情感分析，然后重复上述的步骤，然而从第二次分词时就出现上述问题。
解决方式就是：每次完成一次分词和情感分析后，同时先关闭分词和情感分析，再重新初始化分词和情感分析，进行第二轮的分词和情感分析。
建议：你可以采用上述方法试一下，找准出现问题的代码位置。或者你可以试一下：第二轮前只关闭分词或情感分析，再重新初始化关闭的那一项，再进行第二轮的分词和情感分析，本人没有尝试过，所以只是建议。
